"""
Django settings for clarivo_backend project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env at the project root (Backend-Clarivo/).
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z)-l(00_@s%p(%d_w0uu@$z)a^fh8c@g0afe=0ksi%@y%u=#7%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Extended further down with PUBLIC_HOSTNAME, so the Gmail push webhook
# can be reached through an ngrok tunnel.
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    # Local
    'accounts',
    'projects',
    'documents',
    'detection',
    'chat',
    'mail',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',          # must be before CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clarivo_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clarivo_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# ---------------------------------------------------------------------------
# CORS — django-cors-headers
# ---------------------------------------------------------------------------
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',  # Vite dev server
]


# ---------------------------------------------------------------------------
# AWS — loaded from .env (not used until a later session)
# ---------------------------------------------------------------------------
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
AWS_REGION = os.environ.get('AWS_REGION', '')
S3_BUCKET_NAME = os.environ.get('S3_BUCKET_NAME', '')
DYNAMODB_TABLE_NAME = os.environ.get('DYNAMODB_TABLE_NAME', '')

# ---------------------------------------------------------------------------
# Weaviate Cloud — loaded from .env
# ---------------------------------------------------------------------------
WEAVIATE_URL = os.environ.get('WEAVIATE_URL', '')
WEAVIATE_API_KEY = os.environ.get('WEAVIATE_API_KEY', '')


# ---------------------------------------------------------------------------
# Google OAuth / Gmail — loaded from .env
# ---------------------------------------------------------------------------
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')
GOOGLE_OAUTH_REDIRECT_URI = os.environ.get('GOOGLE_OAUTH_REDIRECT_URI', '')

# Fully-qualified Pub/Sub topic that users.watch publishes change
# notifications to, e.g. 'projects/<gcp-project>/topics/clarivo-gmail'.
GMAIL_PUBSUB_TOPIC = os.environ.get('GMAIL_PUBSUB_TOPIC', '')

# True  -> Gmail pushes to our webhook via Pub/Sub (needs a public hostname).
# False -> the frontend polls the sync endpoint instead.
GMAIL_PUSH_ENABLED = os.environ.get('GMAIL_PUSH_ENABLED', 'False').lower() in (
    'true', '1', 'yes',
)

# Shared secret echoed back in the push subscription's URL, so the webhook
# can tell a real Pub/Sub delivery from anyone who guesses the path.
GMAIL_PUSH_SECRET = os.environ.get('GMAIL_PUSH_SECRET', '')

# Fernet key used to encrypt stored OAuth refresh tokens at rest.
FIELD_ENCRYPTION_KEY = os.environ.get('FIELD_ENCRYPTION_KEY', '')

# Where to send the browser back to once the OAuth consent screen is done.
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# The externally reachable hostname of this backend (an ngrok domain in
# development).  Google's Pub/Sub push arrives with that hostname in the Host
# header, and Django answers an unlisted Host with a flat 400 before the view
# ever runs — so the tunnel domain has to be allowed explicitly.
PUBLIC_HOSTNAME = os.environ.get('PUBLIC_HOSTNAME', '')

if PUBLIC_HOSTNAME:
    # Adding anything at all to ALLOWED_HOSTS switches off the implicit
    # localhost allowance Django grants while DEBUG is on, so the local
    # development hosts have to be re-listed alongside the tunnel.
    ALLOWED_HOSTS += ['localhost', '127.0.0.1', '[::1]', PUBLIC_HOSTNAME]
